### ISSUE TITLE
Add gh bot to repositories

### ISSUE THREAD

**Issue by devsargam** [code100x/github-sol-auto-dispenser#3]

**Comment by devsargam** [comment]
- listen to events in the repo
- comment and reply to messages

**Comment by utnim2** [comment]
> * listen to events in the repo

> * comment and reply to messages



> * listen to events in the repo

> * comment and reply to messages
is there any set of commands that you have thought like `/assign`, `/merge`

**Comment by devsargam** [comment]
Hey @utnim2 thanks for being curious but it's already done : )
