### ISSUE TITLE
make an CONTRIBUTING.md file 

### ISSUE THREAD

**Issue by TanmayDhobale** [code100x/github-sol-auto-dispenser#32]
About this repository how to setup locally

**Comment by Arunsoniiii** [comment]
can i pick this ?

**Comment by TanmayDhobale** [comment]
@Arunsoniiii yup u can

**Comment by TanmayDhobale** [comment]
> can i pick this ?

let me know if u need any help

**Comment by Arunsoniiii** [comment]
@TanmayDhobale I am facing access related error since past 2 days how can i fix this?
