### ISSUE TITLE
UI to track all the expenses yet

### ISSUE THREAD

**Issue by devsargam** [code100x/github-sol-auto-dispenser#5]

**Comment by neutr0n420** [comment]
can I take this one @devsargam ?

**Comment by devsargam** [comment]
sure, but this issue is blocked by a lot other tasks. We are still trying to figure out how are are handling transactions. Can you check on this after some time?

**Comment by neutr0n420** [comment]
Ohk cool but can you guide me to the task that is blocking it maybe I can help there?
